name: Main

on:
  push:
    branches: [main]

env:
  DOCKER_USER: ${{ github.actor }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  REPO_OWNER: ${{ github.repository_owner }}
  SSH_HOST: ${{ secrets.VPS_SSH_HOST }}
  SSH_IP: ${{ secrets.VPS_SSH_IP }}
  SSH_USER: ${{ secrets.VPS_SSH_USER }}
  SSH_PASSWORD: ${{ secrets.VPS_SSH_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install deps
        run: npm ci && go mod download
      - name: Nx Affected Lint
        run: npx nx affected --target=lint --base=remotes/origin/main

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install deps
        run: npm ci && go mod download
      - name: Nx Affected Test
        run: npx nx affected --target=test --base=remotes/origin/main

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install deps
        run: npm ci && go mod download
      - name: Nx Affected Build
        run: npx nx affected --target=build --base=remotes/origin/main
      - name: Upload js artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Download js build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Install deps
        run: npm ci
      - name: Nx Affected Build
        run: npx nx affected --target=deploy --base=remotes/origin/main

  rollout:
    name: rollout
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install deps
        run: npm ci
      - name: Nx Affected Build
        run: npx nx affected --target=deploy --base=remotes/origin/main
