name: PullRequests

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag tanzia
      - name: Login to registry
        run:  docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PAT_TOKEN }}
      - name: Push the docker image
        run: |
          docker tag tanzia ghcr.io/${{ github.repository_owner }}/tanzia:latest
          docker push ghcr.io/${{ github.repository_owner }}/tanzia:latest

  rollout:
    name: rollout
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v4
      - name: ssh into the vps to kubectl rollout restart
        run: sshpass -p "${{ secrets.VPS_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_IP }} -p ${{ secrets.VPS_SSH_PORT }} 'sudo kubectl rollout restart deployment tanzia-app'
