name: Pull Requests

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install deps
        run: npm ci
      - name: Nx Affected Lint
        run: npx nx affected --target=lint --base=remotes/origin/main

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install deps
        run: npm ci
      - name: Nx Affected Test
        run: npx nx affected --target=test --base=remotes/origin/main

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install deps
        run: npm ci
      - name: Nx Affected Build
        run: npx nx affected --target=build --base=remotes/origin/main
