name: Pull Requests

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: actions/setup-node@v4
      - name: Install deps
        run: npm ci
      - name: Nx Affected Lint
        run: npx nx affected --target=lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: actions/setup-node@v4
      - name: Install deps
        run: npm ci
      - name: Nx Affected Test
        run: npx nx affected --target=test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: actions/setup-node@v4
      - name: Install deps
        run: npm ci
      - name: Nx Affected Build
        run: npx nx affected --target=build
